name: Generate DSA Problem (Python)

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-dsa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use your preferred version

      - name: Install dependencies
        run: pip install requests

      - name: Run DSA Generator Script
        run: python generate_dsa_problem.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit the DSA solution
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dsa_solution.py
          git commit -m "Daily Gemini-generated DSA problem"
          git push
